PUBLISHED = [
    dict(key='ADP24', label='Alkadri et al. (ADP24)', venue='ePrint 2024', t=7, structure='t=n',
         rounds=3, online_rounds=3, trans=25.0, vk=7.0, sig=12.0,
         assumption='MLWE, MSIS', interchangeable=False, maxT=7),
    dict(key='ENP24', label='Espitau et al. (Pelican)', venue='ePrint 2024', t=16, structure='t<=n',
         rounds=4, online_rounds=4, trans=364.0, vk=12.8, sig=12.3,
         assumption='RLWE, RSIS', interchangeable=False, maxT=16),
    dict(key='CTZ24', label='Chairattana-Apirom et al.', venue='ASIACRYPT 2024', t=5, structure='t<=n',
         rounds=2, online_rounds=1, trans=1526.0, vk=47.0, sig=258.0,
         assumption='MSIS', interchangeable=False, maxT=32),
    dict(key='GKS24', label='Gur, Katz, Silde', venue='PQCrypto 2024', t=5, structure='t<=n',
         rounds=2, online_rounds=2, trans=3072.0, vk=13.0, sig=46.0,
         assumption='RLWE, RSIS', interchangeable=False, maxT=5),
    dict(key='dPN25', label='del Pino, Niot', venue='PKC 2025', t=8, structure='t<=n',
         rounds=3, online_rounds=3, trans=7.5, vk=2.6, sig=2.7,
         assumption='MLWE, MSIS', interchangeable=False, maxT=8),
    dict(key='TRaccoon', label='Threshold Raccoon', venue='EUROCRYPT 2024', t=1024, structure='t<=n',
         rounds=3, online_rounds=3, trans=40.8, vk=3.9, sig=12.7,
         assumption='MLWE, MSIS', interchangeable=True, maxT=1024),
    dict(key='Che23', label='Chen (DualMS)', venue='CRYPTO 2023', t=1024, structure='t=n',
         rounds=2, online_rounds=1, trans=300.0, vk=10.5, sig=30.9,
         assumption='MLWE, MSIS', interchangeable=False, maxT=1024),
    dict(key='EKT24', label='Espitau et al. (EKT)', venue='CRYPTO 2024', t=1024, structure='t<=n',
         rounds=2, online_rounds=1, trans=276.1, vk=5.5, sig=10.8,
         assumption='AOM-MLWE, MSIS', interchangeable=True, maxT=1024),
    dict(key='Ringtail', label='Ringtail', venue='IEEE S&P 2025', t=1024, structure='t<=n',
         rounds=2, online_rounds=1, trans=612.8, vk=4.5, sig=13.4,
         assumption='MLWE, MSIS', interchangeable=True, maxT=1024),
    dict(key='TalonG', label='TalonG', venue='EUROCRYPT 2026', t=1024, structure='t<=n',
         rounds=2, online_rounds=2, trans=26.9, vk=2.0, sig=17.7,
         assumption='RLWE, RSIS, NTRU', interchangeable=False, maxT=1024),
    dict(key='Hermine', label='Hermine', venue='ePrint 2026', t=64, structure='t<=n',
         rounds=2, online_rounds=1, trans=71.5, vk=2.8, sig=11.0,
         assumption='AOM-MISIS (MLWE, MSIS)', interchangeable=True, maxT=64),
]

COMPLEXITY = [
    dict(key='TRaccoon', keygen='n(k+l)phi log phi', r1='(k+l)phi log phi + t*l*phi',
         r2='t*l*phi', r3='t*l*phi + (k+l)phi log phi', combine='t*l*phi + kl phi log phi',
         verify='kl phi log phi', comm='(2l+k)phi log q + 16t', state='O(Q_sid)'),
    dict(key='Ringtail', keygen='n(k+l)phi log phi', r1='k(l+1)(dbar+1) phi log phi',
         r2='k dbar phi log phi + phi k^2 dbar + 2t l phi', r3='-',
         combine='t l phi + kl phi log phi', verify='kl phi log phi',
         comm='k(dbar+1)phi log q + l phi log q + 16t', state='O(1) per session'),
    dict(key='Tanuki', keygen='n(k+l)phi log phi', r1='k l rep phi log phi',
         r2='k rep phi log phi + 2t l phi', r3='-',
         combine='t l phi + kl phi log phi', verify='kl phi log phi',
         comm='k rep phi log q + l phi log q', state='O(1) per session'),
    dict(key='TalonG', keygen='n phi log phi', r1='phi log phi',
         r2='phi log phi + 4t phi', r3='-', combine='t phi + phi log phi',
         verify='phi log phi', comm='3 phi log q + 2 phi log sigma_r', state='O(1) per session'),
    dict(key='Hermine', keygen='n 2^{log n} (k+l)phi log phi', r1='k l rep phi log phi',
         r2='k rep phi log phi + (k+l)phi log phi', r3='-',
         combine='t(k+l)phi + kl phi log phi', verify='kl phi log phi',
         comm='k rep phi (log q - nu_wp) + (k+l)phi log sigma_z', state='O(1) per session'),
    dict(key='Thimza', keygen='n(k+l)phi log phi', r1='(k+l)phi log phi',
         r2='0', r3='t*l*phi + (k+l)phi log phi', combine='t l phi + kl phi log phi',
         verify='kl phi log phi', comm='(l+k)phi log q - k phi nu_c + 32', state='O(1) per session'),
]
